# Linux x64 and MAC Intel and MAC M1
FROM phpmyadmin:5.2

COPY src /src

# Run initialization scripts
RUN chmod 755 -- /src/*.sh \
    && /src/install-cli-tools.sh \
    && /src/configure-apache.sh \
    && /src/configure-https.sh
